### ISSUE TITLE
instability moving from server to client and back

### ISSUE THREAD

**Issue by despairblue** [symless/synergy-core#4815]
I tested the v1.7.4-stable-ebb7edf, this is one of the bugs I found:
- copy text (can by something short) from the client
- move to the server
- the server stops answering and the client keeps trying to connect

[Here the **complete** logs](https://gist.github.com/despairblue/df72c2f497a3f2be217b)

Another bug I found is the client just exiting, but funny enough this does not happen when the log level is set to debug2 and under other log level the client simply does not output anything useful before exiting. I'm still trying to reproduce this one.

**Comment by despairblue** [comment]
OK, have to carry on tomorrow, since now I have some version of #9 that keeps the windows key and the keys 206 and 207 pressed.

Do you guys have a debugging guide? It's seems most linux issues regarding the clipboard or this sticky keys thingy are hard to reproduce.

**Comment by speaker** [comment]
@despairblue , There isn't a good guide to debugging synergy, but it would be a nice addition to our developer documentation.

**Comment by speaker** [comment]
@despairblue Thank you for the reports, they're very helpful

**Comment by speaker** [comment]
@despairblue Since the build you're using we've added a logging fix as well as a timing fix that might cause the problems you're seeing. Would you be willing to try with the newest GM candidate? http://synergy-project.org/nightly?filter=v1.7.4-stable-267f3ac

**Comment by despairblue** [comment]
Haven't had a problem with 267f3ac yet. I'll keep using it for a while and report back.

Thanks for all your work on this :smiley:

**Comment by VeNoMouS** [comment]
267f3ac is segfaulting for me ...

```
root@wl41988:/tmp# gdb /usr/bin/synergys
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/synergys...(no debugging symbols found)...done.
(gdb) run -f --no-tray --debug INFO --name wl41988 --enable-crypto -c /tmp/qt_temp.L20845 --address :24800
Starting program: /usr/bin/synergys -f --no-tray --debug INFO --name wl41988 --enable-crypto -c /tmp/qt_temp.L20845 --address :24800
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff5c56700 (LWP 21050)]
[New Thread 0x7ffff5455700 (LWP 21051)]
INFO: started server, waiting for clients

Program received signal SIGSEGV, Segmentation fault.
pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:95
95      ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S: No such file or directory.
(gdb) bt
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:95
#1  0x0000000000444a0a in ArchMultithreadPosix::waitCondVar(ArchCondImpl*, ArchMutexImpl*, double) ()
#2  0x00000000004ac1ed in SocketMultiplexer::lockJobListLock() ()
#3  0x00000000004ac414 in SocketMultiplexer::addSocket(ISocket*, ISocketMultiplexerJob*) ()
#4  0x00007ffff4a30c29 in SecureListenSocket::accept() () from /root/.synergy/plugins/libns.so
#5  0x000000000048536a in ClientListener::handleClientConnecting(Event const&, void*) ()
#6  0x000000000044b018 in EventQueue::dispatchEvent(Event const&) ()
#7  0x000000000044e64c in EventQueue::loop() ()
#8  0x0000000000458b13 in ServerApp::mainLoop() ()
#9  0x0000000000456fc7 in ServerApp::runInner(int, char**, ILogOutputter*, int (*)(int, char**)) ()
#10 0x00000000004566b2 in App::run(int, char**) ()
#11 0x00000000004418a6 in main ()
(gdb) 
```

**Comment by despairblue** [comment]
I get a segv als well, but after a couple minutes using it
```
2015-06-24T13:35:24 DEBUG2: writef(CALV)
        /home/despairblue/git/synergy/src/synergy-1.7.4-Source/src/lib/synergy/ProtocolUtil.cpp,36
2015-06-24T13:35:24 DEBUG2: wrote 4 bytes
        /home/despairblue/git/synergy/src/synergy-1.7.4-Source/src/lib/synergy/ProtocolUtil.cpp,87
2015-06-24T13:35:24 DEBUG2: writef(CNOP)
        /home/despairblue/git/synergy/src/synergy-1.7.4-Source/src/lib/synergy/ProtocolUtil.cpp,36
2015-06-24T13:35:24 DEBUG2: wrote 4 bytes
        /home/despairblue/git/synergy/src/synergy-1.7.4-Source/src/lib/synergy/ProtocolUtil.cpp,87
2015-06-24T13:35:24 DEBUG2: msg from server: CALV
        /home/despairblue/git/synergy/src/synergy-1.7.4-Source/src/lib/client/ServerProxy.cpp,125
2015-06-24T13:35:24 DEBUG2: writef(CALV)
        /home/despairblue/git/synergy/src/synergy-1.7.4-Source/src/lib/synergy/ProtocolUtil.cpp,36
2015-06-24T13:35:24 DEBUG2: wrote 4 bytes
        /home/despairblue/git/synergy/src/synergy-1.7.4-Source/src/lib/synergy/ProtocolUtil.cpp,87
2015-06-24T13:35:24 DEBUG2: writef(CNOP)
        /home/despairblue/git/synergy/src/synergy-1.7.4-Source/src/lib/synergy/ProtocolUtil.cpp,36
2015-06-24T13:35:24 DEBUG2: wrote 4 bytes
        /home/despairblue/git/synergy/src/synergy-1.7.4-Source/src/lib/synergy/ProtocolUtil.cpp,87
2015-06-24T13:35:24 DEBUG1: disconnected
        /home/despairblue/git/synergy/src/synergy-1.7.4-Source/src/lib/client/Client.cpp,654
2015-06-24T13:35:24 INFO: disconnected from server
        /home/despairblue/git/synergy/src/synergy-1.7.4-Source/src/lib/synergy/ClientApp.cpp,324
2015-06-24T13:35:24 DEBUG: retry in 1 seconds
        /home/despairblue/git/synergy/src/synergy-1.7.4-Source/src/lib/synergy/ClientApp.cpp,284
2015-06-24T13:35:24 DEBUG1:   target STRING (31)
        /home/despairblue/git/synergy/src/synergy-1.7.4-Source/src/lib/platform/XWindowsClipboard.cpp,1475
2015-06-24T13:35:24 DEBUG1:   got data, 381 bytes
        /home/despairblue/git/synergy/src/synergy-1.7.4-Source/src/lib/platform/XWindowsClipboard.cpp,1481
2015-06-24T13:35:24 DEBUG1: request succeeded
        /home/despairblue/git/synergy/src/synergy-1.7.4-Source/src/lib/platform/XWindowsClipboard.cpp,1361
2015-06-24T13:35:24 DEBUG:   added format 0 for target STRING (31) (381 bytes)
        /home/despairblue/git/synergy/src/synergy-1.7.4-Source/src/lib/platform/XWindowsClipboard.cpp,561
2015-06-24T13:35:24 DEBUG: close clipboard 1
        /home/despairblue/git/synergy/src/synergy-1.7.4-Source/src/lib/platform/XWindowsClipboard.cpp,354
fish: “synergyc -f --debug DEBUG2 --na…” terminated by signal SIGSEGV (Address boundary error)
```

Using the nightly from two days ago.

**Comment by speaker** [comment]
@XinyuHou Does this look familiar?

**Comment by speaker** [comment]
@VeNoMouS Does this happen right on startup every time or is it intermittent?  What Linux are you running? Did you build from source, or just using the rpm image?

@despairblue Is it reliable, or just a random thing?

We've not seen these issues in house, that's why I'm asking.

**Comment by Trucido** [comment]
I've also seen some synergyc seg faults on linux which seem to only happen with logging set to FATAL. copy+paste is horribly broken for me to a windows synergys/synergyd, even with/without the new disable-drag-drop. I'll try DEBUG2 and see if i get anything interesting.

**Comment by Trucido** [comment]
posted a log in #4327 with a segfault, but i think this is definitely related to clipboard now. when the client gets stoned and won't reconnect the log is stuck on "request selection=CLIPBOARD"

full log of what occurred before the client got stoned http://pastebin.com/vAXGmZts

**Comment by VeNoMouS** [comment]
@speaker at start , Debian 8.1 x64
